language: node_js
node_js:
  - node
os: 
  - osx
  - windows

script:
  - yarn install
  - yarn dist

deploy:
  provider: s3
  access_key_id: $Access_Key
  secret_access_key: $Secret_key
  bucket: electron-auto-update-test
  upload-dir: travis
  skip_cleanup: true
  local_dir: release

