name: Build Electron app
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build-osx
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          version: 10
      # - run: brew install awscli
      - run: aws --version
      - run: aws configure aws_access_key_id=$AWS_ACCESS_KEY aws_secret_access_key=$AWS_SECRET_KEY
      - run: npm install
      - run: npm run dist
      - run: npm run release
