name: Build Electron app
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build-osx
    strategy:
      matrix:
        platform: [macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          version: "10.x"
      - name: Install CLI
        run: brew install awscli
        if: matrix.platform == 'macos-latest'
      # - run: aws configure aws_access_key_id=$AWS_ACCESS_KEY aws_secret_access_key=$AWS_SECRET_KEY
      # - run: npm install
      # - run: npm run dist
