name: Build Electron app
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build-osx
    strategy:
      matrix:
        platform: [macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          version: "10.x"
      - name: Install AWS CLI Mac
        run: brew install awscli
        if: matrix.platform == 'macos-latest'
      - name: Install AWS CLI Windows
        run: pip3 install awscli
        if: matrix.platform == 'windows-latest'
      # - name: install dependencies
      #   run: npm install
      # - name: build the app
      #   run: npm run dist
      # - name: copy on windows
      #   env:
      #     BUILD_DATE: date /t
      #   run: cp s3 release/ s3://electron-auto-update-test/%BUILD_DATE%/ --exclude "*" --include "*.exe"
      #   if: matrix.platform == 'windows-latest'
      # - name: copy on mac
      #   env:
      #     BUILD_DATE: date "+%d/%m/%y"
      #   run: cp s3 release/ s3://electron-auto-update-test/$BUILD_DATE/ --exclude "*" --include "*.dmg"
      #   if: matrix.platform == 'macos-latest'
      - name: copy
        env:
          AWS_ACCESS_KEY_ID: AKIAUDVEVXEO2HATLD6S
          AWS_SECRET_ACCESS_KEY: 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
        run: aws s3 cp package.json s3://electron-auto-update-test/test/
